import { Lang } from './Lang';
import { TranslatorType } from './TranslatorType';
import { UserEntities } from './UserEntities';
export interface User {
  id?: number;
  id_str?: string;
  name?: string;
  screen_name?: string;
  location?: string;
  description?: string;
  url?: null | string;
  entities?: UserEntities;
  protected?: boolean;
  followers_count?: number;
  friends_count?: number;
  listed_count?: number;
  created_at?: string;
  favourites_count?: number;
  utc_offset?: null;
  time_zone?: null;
  geo_enabled?: boolean;
  verified?: boolean;
  statuses_count?: number;
  lang?: Lang;
  contributors_enabled?: boolean;
  is_translator?: boolean;
  is_translation_enabled?: boolean;
  profile_background_color?: string;
  profile_background_image_url?: null | string;
  profile_background_image_url_https?: null | string;
  profile_background_tile?: boolean;
  profile_image_url?: string;
  profile_image_url_https?: string;
  profile_banner_url?: string;
  profile_link_color?: string;
  profile_sidebar_border_color?: string;
  profile_sidebar_fill_color?: string;
  profile_text_color?: string;
  profile_use_background_image?: boolean;
  has_extended_profile?: boolean;
  default_profile?: boolean;
  default_profile_image?: boolean;
  following?: null;
  follow_request_sent?: null;
  notifications?: null;
  translator_type?: TranslatorType;
}
